server:
  servlet:
    context-path: /subscription-service

spring:
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: pass123!
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
#  quarkus:
#  resteasy:
#    gzip:
#      enabled: true
#      max-input: 10M
#  datasource:
#    db-kind: h2
#    jdbc:
#      url: "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
#      max-size: 4
#    username: "sa"
#    password: "pass123!"
#    db-kind: postgresql
#    jdbc:
#      url: "jdbc:postgresql://localhost:5432/postgres"
#      max-size: 4
#      driver: org.postgresql.Driver
#    username: "postgres"
#    password: "postgressu"
#  hibernate-orm:
#    database:
#      generation: drop-and-create
#    log:
#      sql: true
#      format-sql: true
#      jdbc-warnings: true
#  log:
#    category:
#      "org.hibernate":
#        level: TRACE

